### ISSUE TITLE
Each portfolio project should include a footer & link to code

### ISSUE THREAD

**Issue by Grae-Drake** [dbrusky1/my-dev-port#2]
You want to make it easy for users to find your code and your info again.  Footers with links back to your site and to the code solves that problem and also adds professional polish to each project.

**Comment by dbrusky1** [comment]
Hey   I'm sorry but I'm experiencing an internet outage at my house.   Can we meet another time.

**Comment by Grae-Drake** [comment]
Hey man, yeah, I'm sorry to hear that.  I'd like to meet as soon as
possible and my calendar's filling up this week.  Are you available at
10:30am tomorrow?

On Tue, Jun 7, 2016 at 12:10 PM, Daniel Brusky <notifications@github.com>
wrote:

> Hey I'm sorry but I'm experiencing an internet outage at my house. Can we
> meet another time.
>
> Sent from my iPhone
>
> > On Jun 7, 2016, at 11:16 AM, Grae Drake <notifications@github.com>
> wrote:
> >
> > You want to make it easy for users to find your code and your info
> again. Footers with links back to your site and to the code solves that
> problem and also adds professional polish to each project.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dbrusky1/my-dev-port/issues/2#issuecomment-224330764>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE24agMLBbzrRzbwbDCG9ksM8V-BW91Bks5qJZfZgaJpZM4IwCdV>
> .
>



-- 
Grae Drake
Head of Education at Thinkful
grae@thinkful.com <Grae@thinkful.com>

**Comment by dbrusky1** [comment]
Hey Grae,

this is my resume edited based on your input....thanks for the thorough
edit!!

**Comment by dbrusky1** [comment]
Got it thanks!
